package info.lun4rsoft.jj25.files;

/**
 * Abstract class specifying behaviour that all classes representing files must include.
 * @author wKtK
 * @version 1.0.0.0
 */
public abstract class JazzFile {
	/**
	 * Reads the data from disk, using a full absolute path. Usage of a Filepool is preferred over this.
	 * @param fullpath The absolute path to the file. Make sure to use local separators.
	 * @return A boolean, true if successful, otherwise false.
	 */
	public abstract boolean ReadFromFile(String fullpath);
	/**
	 * <i>Added later when Filepools work</i>
	 * @param name
	 * @param checkCached
	 * @return 
	 */
	public abstract boolean ReadFromFilePool(String name,boolean checkCached);
	
	/**
	 * Writes the data back to disc, using a full absolute path. Usage of a Filepool is preferred over this.
	 * @param fullpath The absolute path to the file. Make sure to use local separators.
	 * @return A boolean, true if successful, otherwise false.
	 */
	public abstract boolean WriteToFile(String fullpath);
	/**
	 * <i>Added later when Filepools work</i>
	 * @param name
	 * @param toCached
	 * @return
	 */
	public abstract boolean WriteToFilePool(String name,boolean toCached);
	
	/**
	 * Returns the last errorcode generated by a function.
	 * @return The errorcode.
	 */
	public abstract int getError();
}
